/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Concat */

#ifndef _Included_Concat
#define _Included_Concat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Concat
 * Method:    concat
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Concat_concat
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
