/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyAppJNI */

#ifndef _Included_MyAppJNI
#define _Included_MyAppJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyAppJNI
 * Method:    concat
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MyAppJNI_concat
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
